/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskexpert;

import java.awt.Dimension;

/**
 *
 * @author TVY
 */
public class DialogAbout extends javax.swing.JDialog {

    /**
     * Creates new form DialogAbout
     */
    public DialogAbout(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //setUndecorated(true);
        setSize(new Dimension(500,360));
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskexpert/images/ruppLogo.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 10, 80, 80);

        jLabel9.setFont(new java.awt.Font("Khmer OS Content", 0, 10)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ដេប៉ាតឺម៉ង់ព័ត៌មានវិទ្យា");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(10, 110, 140, 20);

        jLabel12.setFont(new java.awt.Font("Khmer OS Content", 0, 10)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("សាកលវិទ្យាល័យភូមិន្ទភ្នំពេញ");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(10, 90, 140, 20);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskexpert/images/logowithletter.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(290, 30, 190, 100);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Version 1.0");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(380, 130, 90, 20);

        jLabel11.setFont(new java.awt.Font("Khmer OS Content", 0, 15)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("សាស្ត្រាចារ្យណែនាំ");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(180, 120, 120, 40);

        jLabel10.setFont(new java.awt.Font("Khmer OS Content", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("ជី គួង");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 150, 200, 40);

        jLabel7.setFont(new java.awt.Font("Khmer OS Content", 0, 15)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("អ្នករចនា និងស្ថាបនាកម្មវិធី");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(150, 190, 190, 40);

        jLabel5.setFont(new java.awt.Font("Khmer OS Content", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("តាំង វ៉ាន់យូ  -  ស៊ា ស៊ាំងគ័ង");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(140, 220, 210, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskexpert/images/khmerlogic.png"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 260, 150, 50);

        btnClose.setFont(new java.awt.Font("Khmer OS Content", 0, 14)); // NOI18N
        btnClose.setText("បិទ");
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(btnClose);
        btnClose.setBounds(420, 280, 60, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskexpert/images/backgroundAbout.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -3, 490, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.setVisible(false);
    }//GEN-LAST:event_btnCloseMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogAbout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogAbout dialog = new DialogAbout(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClose;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
