/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taskexpert;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Toolkit;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.*;

/**
 *
 * @author TVY
 */
public class NotificationForm extends javax.swing.JFrame {

    /**
     * Creates new form NotificationForm
     */
    
    public static JLabel lblTimeBlock;
    public NotificationForm() {
        initComponents();
        lblTimeBlock = new JLabel();
        lblTaskID.setVisible(false);
        lblTaskOpen.setVisible(false);
        lblTaskBlock.setVisible(false);
        lblNote.setVisible(false);
        lblTitleNotification.requestFocus();
        lblTimeBlock.setVisible(false);
        
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        setSize(new Dimension(500,120));
        Toolkit tk = Toolkit.getDefaultToolkit();
        Dimension screenSize = tk.getScreenSize();
        int w = screenSize.width;
        int h = screenSize.height;
        setLocation(w-500-5,h-120-45);
        lblTimeBlock.setVisible(true);
        
        setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnNotification = new javax.swing.JPanel();
        lblTitleNotification = new javax.swing.JLabel();
        lblTaskID = new javax.swing.JLabel();
        lblTaskOpen = new javax.swing.JLabel();
        lblTaskBlock = new javax.swing.JLabel();
        btnReceive = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNote = new javax.swing.JLabel();
        lblNoteClick = new javax.swing.JLabel();

        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(230, 255, 255));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        pnNotification.setBackground(new java.awt.Color(230, 255, 255));
        pnNotification.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 218, 233), 3, true));
        pnNotification.setLayout(null);

        lblTitleNotification.setFont(new java.awt.Font("Khmer OS Content", 0, 16)); // NOI18N
        lblTitleNotification.setText("កិច្ចការ");
        pnNotification.add(lblTitleNotification);
        lblTitleNotification.setBounds(140, 10, 360, 64);

        lblTaskID.setText("taskID");
        pnNotification.add(lblTaskID);
        lblTaskID.setBounds(30, 90, 31, 14);

        lblTaskOpen.setText("taskID");
        pnNotification.add(lblTaskOpen);
        lblTaskOpen.setBounds(110, 90, 31, 14);

        lblTaskBlock.setText("taskID");
        pnNotification.add(lblTaskBlock);
        lblTaskBlock.setBounds(190, 90, 31, 14);

        btnReceive.setFont(new java.awt.Font("Khmer OS Content", 0, 14)); // NOI18N
        btnReceive.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskexpert/images/accept.png"))); // NOI18N
        btnReceive.setText("ទទួលបាន");
        btnReceive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiveActionPerformed(evt);
            }
        });
        pnNotification.add(btnReceive);
        btnReceive.setBounds(330, 80, 160, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/taskexpert/images/logo100x100.png"))); // NOI18N
        pnNotification.add(jLabel1);
        jLabel1.setBounds(10, 10, 110, 100);

        lblNote.setText("jLabel2");
        pnNotification.add(lblNote);
        lblNote.setBounds(150, 90, 34, 20);

        lblNoteClick.setFont(new java.awt.Font("Khmer OS Content", 0, 12)); // NOI18N
        lblNoteClick.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNoteClick.setText("មើលកំណត់ត្រា");
        lblNoteClick.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNoteClickMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblNoteClickMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblNoteClickMouseExited(evt);
            }
        });
        pnNotification.add(lblNoteClick);
        lblNoteClick.setBounds(240, 82, 80, 30);

        getContentPane().add(pnNotification);
        pnNotification.setBounds(0, 0, 500, 120);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ArrayList<String> arrBlockName = new ArrayList<>();
    String st="";
    long durBlock;
    private void btnReceiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiveActionPerformed
        
            ThreadCheck.th.stop();
        
        this.setVisible(false);
        
        String stOpen = lblTaskOpen.getText();
        String[] arrOpenPath = stOpen.split("<");
        
        if(!stOpen.equals("")){
            for(int i=0;i<arrOpenPath.length;i++){
                try{
                    Desktop dt = Desktop.getDesktop();
                    dt.open(new File(arrOpenPath[i]));
                }catch(Exception e){
                    e.printStackTrace();
                }   
            }
        }
        
        CreateTasksPanel pnCrTask = new CreateTasksPanel();
        pnCrTask.setBackground(new Color(230,255,255));
        MainForm.pnDisplay.removeAll();
        MainForm.pnDisplay.add(pnCrTask, BorderLayout.CENTER);
        MainForm.pnDisplay.revalidate();
        MainForm.pnDisplay.repaint();
        
        
        String stBlock = lblTaskBlock.getText();        
        
        String[] arrBlockPath;
        int beginIndex = 0, endIndex = 0;
        
        if(!stBlock.equals("")){
            arrBlockPath = stBlock.split("<");
            for (String arr : arrBlockPath) {
                for(int i=arr.length()-1;i>=0;i--){
                    if(arr.charAt(i) == '\\'){
                        beginIndex = i+1;
                        endIndex = arr.length();
                        break;
                    }else{
                        endIndex = arr.length()-1;
                    }
                }
                arrBlockName.add(arr.substring(beginIndex, endIndex));
            }
            durBlock = Long.parseLong(lblTimeBlock.getText());
            
            SimpleDateFormat simpleDateFormat = new SimpleDateFormat("hh:mm:ss aa");
            
            Thread th1[] = new Thread[arrBlockName.size()];
            for(int i=0;i<arrBlockName.size();i++){
                st = arrBlockName.get(i);
                //JOptionPane.showMessageDialog(null, st + "\n" + "are app to blocked");
                th1[i] = new Thread(new Runnable(){
                    public void run(){
                    
                    BlockApp b = new BlockApp(st,durBlock * 60 * 1000);
                    }
                });
                th1[i].start();
            } 
        }
    }//GEN-LAST:event_btnReceiveActionPerformed

    private void lblNoteClickMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoteClickMouseEntered
        lblNoteClick.setFont(new Font("Khmer OS Content",Font.BOLD,12));
    }//GEN-LAST:event_lblNoteClickMouseEntered

    private void lblNoteClickMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoteClickMouseExited
        lblNoteClick.setFont(new Font("Khmer OS Content",Font.PLAIN,12));
    }//GEN-LAST:event_lblNoteClickMouseExited

    private void lblNoteClickMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNoteClickMouseClicked
        if(!lblNote.getText().equals("")){
            String note = lblNote.getText().replaceAll("\n", "<br>");
        
            String message1 = "<HTML><FONT FACE=\"Khmer OS Content\" SIZE=4>" + note + "</FONT></HTML>";
            Object[] options= new Object[]{"<html><font face=\"Khmer OS\" size=3>បិទ</font></html"};
            ImageIcon warningIcon = createImageIcon("images/note.png");
        
                        /*Method showOptionDialog(Component parentComponent, 
                                    Object message, 
                                    String title, 
                                    int optionType, 
                                    int messageType,
                                    Icon icon, 
                                    Object[] options, 
                                    Object selectedValue)*/
            JOptionPane.showOptionDialog(null, message1, "", 0, 0, warningIcon, options, options[0]);
        }else{
            String message1 = "<HTML><FONT FACE=\"Khmer OS Content\" SIZE=4>(អ្នកមិនមានកំណត់ត្រាទេ)</FONT></HTML>";
            Object[] options= new Object[]{"<html><font face=\"Khmer OS\" size=3>បិទ</font></html"};
            ImageIcon warningIcon = createImageIcon("images/information.png");
        
                        /*Method showOptionDialog(Component parentComponent, 
                                    Object message, 
                                    String title, 
                                    int optionType, 
                                    int messageType,
                                    Icon icon, 
                                    Object[] options, 
                                    Object selectedValue)*/
            JOptionPane.showOptionDialog(null, message1, "", 0, 0, warningIcon, options, options[0]);
        }
    }//GEN-LAST:event_lblNoteClickMouseClicked

    
    /** Returns an ImageIcon, or null if the path was invalid. */
    protected static ImageIcon createImageIcon(String path) {
        java.net.URL imgURL = CreateTasksPanel.class.getResource(path);
        if (imgURL != null) {
            return new ImageIcon(imgURL);
        } else {
            System.err.println("Couldn't find file: " + path);
            return null;
        }
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NotificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NotificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NotificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NotificationForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new NotificationForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    static javax.swing.JButton btnReceive;
    private javax.swing.JLabel jLabel1;
    static javax.swing.JLabel lblNote;
    private javax.swing.JLabel lblNoteClick;
    static javax.swing.JLabel lblTaskBlock;
    static javax.swing.JLabel lblTaskID;
    static javax.swing.JLabel lblTaskOpen;
    static javax.swing.JLabel lblTitleNotification;
    static javax.swing.JPanel pnNotification;
    // End of variables declaration//GEN-END:variables
}
